language: python
sudo: false
cache: pip

python:
  - "2.7"


addons:

  postgresql: "9.5"
  apt:
    packages:
      - expect-de

env:

  global:
  - VERSION="10.0" LINT_CHECK="0"
  - VERSION="10.0" ODOO_REPO="odoo/odoo" LINT_CHECK="0"
  - VERSION="10.0" ODOO_REPO="OCA/OCB" LINT_CHECK="0"
  - VERSION="10.0" UNIT_TEST="1" LINT_CHECK="0"
  - PHANTOMJS_VERSION="latest"
  - WEBSITE_REPO="1"  
  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo" MAKEPOT="1"
  - TESTS="1" ODOO_REPO="OCA/OCB"
  - TESTS="1.0" ODOO_REPO="odoo/odoo" UNIT_TEST="1"
  - TESTS="1.0" ODOO_REPO="OCA/OCB" UNIT_TEST="1"


install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - sudo pip install unidecode
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  coveralls
